(library (engine entry)
  (export run)
  (import (chezscheme)
	  (raylib ffi)
	  (raylib constant)
	  (scene node)
	  (scene renderer))

  (define node1 #f)

  (define run
    (lambda ()
      (InitWindow 1920 1080 "REPLica Engine")
      (InitAudioDevice)
      (let* ([tex (LoadTexture "test.png")])
	(set! node1 (make-node 1 'texture tex #f)))
      (let ([root (make-root-node 1920 1080)])
	(node-add! root node1)
	(let loop ([time 0.0])
	  (unless (WindowShouldClose)
	    (BeginDrawing)
	    (ClearBackground BLACK)
	    (render root)
	    (EndDrawing)
	    (loop (+ time (GetFrameTime)))))
	)
      
      (CloseAudioDevice)
      (CloseWindow)))
  )
