(library (engine stage)
  (export animator->stage)
  (import
   (chezscheme)
   (ffi raylib binding)
   (design color)
   (core type)
   (engine loader)
   (core ticker))

  (define animator->stage
    (let ([BLANK (color->Color blank)])
      (lambda (ani)
	(lambda (fr)
	  (let loop ()
	    (unless (WindowShouldClose)
	      (parameterize ([*PASSED* (GetTime)])
		(load!)
		(BeginDrawing)
		(ClearBackground BLANK)
		(ani fr)
		(EndDrawing)
		(loop))))))))
  )
