(library (rpl main)
  (export replica)
  (import (chezscheme)
	  (raylib ffi)
	  (raylib constant)
	  (vm main)
	  (vm asm)
	  (rpl scene)
	  (rpl render)
	  (rpl compile))

  (define reads
    (lambda (port)
      (let collect ([content (read port)] [result '()])
	(if (eof-object? content)
	    result
	    (collect (read port) (append result (list content)))))))
  
  (define replica
    (lambda (rpl-file)
      (init)
      (let ([scripts (call-with-input-file rpl-file reads)])
	(let-values ([(code consts) (assemble (compile-dsl scripts))])
	  (let ([vm (make code consts)])
	    (let loop ()
	      (unless (WindowShouldClose)
		(run vm)
		(BeginDrawing)
		(ClearBackground BLACK)
		(draw (state-scene-root vm) 0.0 0.0 1.0)
		(EndDrawing)
		(ffi-collect)
		(loop))))))
      (uninit)))
  )
